services:
  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: akashkv11
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: postgress
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: akash11skz@gmail.com
      PGADMIN_DEFAULT_PASSWORD: akashkv
    ports:
      - '80:80'
    depends_on:
      - db

volumes:
  postgres_data:
